### ISSUE TITLE
_rnAppleHealthKit.default.initHealthKit is not a function

### ISSUE THREAD

**Issue by chiragbhardwaj** [lucaspbordignon/rn-apple-healthkit#102]
I'm continuously getting this error. I've granted all the permissions and followed every step mentioned. Still getting this error

import AppleHealthKit from 'rn-apple-healthkit';

const PERMS = AppleHealthKit.Constants.Permissions;
const UNITS = AppleHealthKit.Constants.Units;

const options = {
 permissions: {
read: [PERMS.Weight, PERMS.SleepAnalysis]
}
};

AppleHealthKit.initHealthKit(options, (err, results) => {
  if (err) {
      console.log("error initializing Healthkit: ", err);
      return;
  }
  AppleHealthKit.getDateOfBirth(null, (err, results) => {
    if (this._handleHealthkitError(err, 'getDateOfBirth')) {
      return;
    }
      console.log(results)
    });

});
// Generated using react-native init command
const App = () => {
  return (
    <Fragment>
      <StatusBar barStyle="dark-content" />
      <SafeAreaView>
         <ScrollView
          contentInsetAdjustmentBehavior="automatic"
           style={styles.scrollView}>
           <Header />
          {global.HermesInternal == null ? null : (
            <View style={styles.engine}>
              <Text style={styles.footer}>Engine: Hermes</Text>
            </View>
          )}
    </ScrollView>
  </SafeAreaView>
    </Fragment>
  );
};

const styles = StyleSheet.create({
//Auto-generated styling here
});
export default App;

**Comment by amitsri** [comment]
Extract attached file and copy it in the node_modules/rn-apple-healthkit folder and then go to ios folder and execute "pod install"

![Screen Shot 2019-09-12 at 4 19 22 PM](https://user-images.githubusercontent.com/286363/64778214-45c7ec80-d579-11e9-9bcb-98124d458ebe.png)


[rn-apple-healthkit.podspec.zip](https://github.com/terrillo/rn-apple-healthkit/files/3605037/rn-apple-healthkit.podspec.zip)

**Comment by JoelOnGithub** [comment]
This is specifically for react-native 0.60+, where react-native link rn-apple-healthkit is no longer allowed

**Comment by Luke-Gurgel** [comment]
This is not really specific to react native 0.60 since projects that are using a lower version can also use cocoapods to manage dependencies. In react native 0.60, [cocoapods became the default way to do so](https://facebook.github.io/react-native/blog/2019/07/03/version-60#cocoapods-by-default).

Also, moving forward, the team that's working on the react native cli[ will deprecate `react-native link`](https://github.com/react-native-community/cli/blob/master/docs/commands.md#link), but it should still be allowed, as well as manual linking, because there are projects that don't support auto-linking yet. 

For example, [this doc](https://github.com/react-native-community/upgrade-helper/issues/47#issue-463784095) is pretty helpful for upgrading a project from 0.5x.x to 0.60.x, and near the end, it mentions that you should leave libs that you linked (that don't support auto-linking) in the Libraries folder (for now).

In fact, if you want to disable auto-linking for certain libs before installing them, you can set up a `react-native.config.js` file [like this](https://github.com/react-native-community/cli/blob/master/docs/autolinking.md#how-can-i-disable-autolinking-for-unsupported-library).

**Comment by chiragbhardwaj** [comment]
I started developing the Healthkit app in Swift5. I'm closing this issue as I believe the steps mentioned in thread above will work and be helpful to someone trying to do this in react native.

Thank you.

**Comment by jacques-cadet** [comment]
Didn't work for me, may be because I'm using expo. But it didn't
