### ISSUE TITLE
1.0v (Rewrite)

### ISSUE THREAD

**Issue by terrillo** [lucaspbordignon/rn-apple-healthkit#120]
Hey everyone,

I'm currently working on a small rewrite of this plugin. The goal is to improve maintainability, support newer version of React Native and Health Kit API, and provide a working Demo app. No ETA yet and not ready for any testing. 

Link to pull request -> https://github.com/terrillo/rn-apple-healthkit/pull/118

**Comment by bobbydeveaux** [comment]
Hey,
There were a few outstanding pull requests that we needed as you were a little quiet, so I forked and cloned/copied to re-hash and I've also added some of my own stuff..!  https://github.com/awsmlabs/rn-apple-healthkit

Happy to raise PR for you to merge anything in, it has a critical bug fix for NutritionDaily samples too. 

Not sure if there's much point if you're doing a re-write though?

Let me know if you need any help/testers - using this library extensively atm!

**Comment by younss** [comment]
Can you add please background fetch

**Comment by terrillo** [comment]
Hey @bobbydeveaux I’ll take a look at the your fork. I do plan to have more releases before the rewrite. Not having the best luck getting the package to work well with RN 0.60+. 

This is also a good time to add iOS version control support. For example, some data like Mindfulness can’t be pulled in older versions of iOS. 

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by terrillo** [comment]
@younss top I list. 😊 I can really use this feature for a side project 

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by JulianKingman** [comment]
@terrillo @younss I've implemented background fetch for a few sources in [my fork](https://github.com/JulianKingman/rn-apple-healthkit), and it's working well (in production). I have some work to get it ready for an upstream merge however.

Other things added to my branch that I would love to move upstream are statistics queries (queries for different time periods) and anchored queries (ongoing queries that only fetch new data).

I think, however, that this library really needs a good refactor, particularly with the API, which I think is a bit clunky. For example, creating a general data getter function, instead of unique functions for each data source, would make it much easier to use. @terrillo is that in the cards for your re-write plans? What's your thinking?

Thanks!

**Comment by Frans-L** [comment]
Hey @terrillo ! I really appreciate your work!  🙌 

Any updates regarding of this update? By looking at the dates, it seems like no one is working on the update anymore?
