### ISSUE TITLE
initHealthKit responds with no err and res=1 even when user declines the access

### ISSUE THREAD

**Issue by skb1129** [lucaspbordignon/rn-apple-healthkit#58]
I tried running it on the simulator as well as a real device, the `initHealthKit` always returns no `err` and `res = 1` in the callback function so there is no way to know if the user actually gave HealthKit permissions or not.

**Comment by Kiran0791** [comment]
Same issue. Is there a way to know the permission status

**Comment by EJohnF** [comment]
actually, there is no way to know it. 

from here https://developer.apple.com/documentation/healthkit/setting_up_healthkit


> To help protect the user’s privacy, your app does not know whether the user granted or denied permission to read data from HealthKit. If the user denied permission, attempts to query data from HealthKit return only samples that your app successfully saved to the HealthKit store.

I just can suggest you check:
1. Is write permission granted?
2. After retrieving data - is there any records during last week? 

If both are false, most probably user denied read access. But these checks are not the library responsibility - since you may wish to rely on some other checks.
